# Generated by Django 5.0.1 on 2025-02-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_order_created_at_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor_token',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
