# Generated by Django 5.1.5 on 2025-02-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy", "0003_remove_order_phone_number_remove_order_vendor_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
